AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'Gemfile'
    - 'app/controllers/registrations_controller.rb'
    - 'app/controllers/sessions_controller.rb'
    - 'app/controllers/codeship_controller.rb'
Style/Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 100
Style/WordArray:
  Enabled: false
